language: python
python: 3.6
 
env:
  global:
  - TC_HOME=$HOME/tc
  - MBED_BUILD_TIMESTAMP=42
  - BUILD_DIR=cloud_client 

matrix:
  include:
  - os: linux
    env: MBED_CLOUD=1.5.0 ARMGCC_VERSION=6.3.1
  - os: linux
    env: MBED_CLOUD=2.0.1.1 ARMGCC_VERSION=6.3.1
  - os: linux
    env: MBED_CLOUD=2.0.1.1 ARMGCC_VERSION=7.3.1
 
cache:
  pip: true
  directories:
    - $HOME/.cache/apt
 
after_success:
  #- bash -c "$STATUS" success "Build $TARGET has passed"
 
after_failure:
  #- bash -c "$STATUS" failure "Build $TARGET has failed"
 
before_install:
  #- bash -c "$STATUS" pending "Build $TARGET in progress"
  # Make sure pipefail
  #- set -o pipefail
  # Setup apt to cache
  #- mkdir -p $HOME/.cache/apt/partial
  #- sudo rm -rf /var/cache/apt/archives
  #- sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
  # Setup ppa to make sure arm-none-eabi-gcc is correct version
  #- sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  #- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  #- travis_retry $(! sudo apt-get update 2>&1 | grep FAILED )
  #- sudo pip install --upgrade pip 
  - sudo pip install -U pip wheel
  - sudo pip install mbed-cli
  - sudo mbed deploy
install:
  # Print versions we use
  - gcc --version
  - python --version
  # Install dependencies
  - sudo apt-get install gcc-arm-embedded
  - arm-none-eabi-gcc --version
  # Deploy mbed and pip dependencies
  - sudo pip install mbed-cli
  - sudo mbed deploy --verbose
  - sudo mbed new .
  #- sudo pip install -r mbed-os/requirements.txt
  - sudo pip install colorama jinja2 intelhex junit_xml mbed_ls mbed_host_tests mbed_greentea beautifulsoup4 fuzzywuzzy pyelftools jsonschema future mbed_cloud_sdk icetea
 
script:
  # Check that example compiles with littlefs + spif
  - mbed compile -t GCC_ARM -m K82F -j0
 
  # Check that example compiles with fatfs + sd
  - sed -i 's/SPIFBlockDevice bd/SDBlockDevice bd/g' main.cpp
  - sed -i 's/MBED_CONF_SPIF_DRIVER/MBED_CONF_SD/g' main.cpp
  - sed -i 's/LittleFileSystem fs/FATFileSystem fs/g' main.cpp
  - mbed compile -t GCC_ARM -m K64F -j0
